name: openrouter_dart
description: A Dart client for OpenRouter API. Supports Chat, Streaming, Tools, Vision, Embeddings, and Reranking.
version: 1.0.1
repository: https://github.com/wkqw1/openrouter_dart

environment:
  sdk: ^3.11.4

# Add regular dependencies here.
dependencies:
  dio: ^5.9.2
  path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6